"""empty message

Revision ID: 3684de5927a1
Revises: 497bdedb3272
Create Date: 2024-12-11 09:22:05.832682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3684de5927a1'
down_revision: Union[str, None] = '497bdedb3272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('loccode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locationname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('loccode')
    )
    op.create_table('purchorders12',
    sa.Column('orderno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplierno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orddate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requisitionno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orderref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urltracking', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deladd1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deladd2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deladd3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intostocklocation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('orderno')
    )
    op.create_table('suppliers',
    sa.Column('supplierid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suppname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('supplierid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    op.drop_table('purchorders12')
    op.drop_table('locations')
    # ### end Alembic commands ###
